from __future__ import annotations

import contextlib
import json
import warnings
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from data.models import EntryPlanRecord, FundamentalRecord, PriceBar
from strategies.factor_aqr import RankedFactor, aqr_rank_for, aqr_ranked
from valuation.composite import composite_fair_value, confidence_from_dispersion
from valuation.confidence import ConfidenceBreakdown, calibrated_confidence
from valuation.dcf import discounted_cash_flow
from valuation.entry import average_true_range_pct, make_entry_plan
from valuation.multiples import fair_value_from_pb, fair_value_from_pe

# A confluence read needs enough history for swing-structure / volume-profile detectors to be
# meaningful. Below this the chart engine produces noise, so we report no chart opinion at all.
_MIN_CHART_BARS = 40


@dataclass(frozen=True)
class ValidatedStrategy:
    """The validated anchor strategy whose reliability calibrates confidence.

    Populated from out/MASTER-REPORT-2008-2026.md (the gate-approved IDEAL baseline)
    and regenerated by the P3 re-validation harness. ``top_n`` is the count of names
    the strategy actually holds, so rank <= top_n means "the strategy would buy this".
    """

    strategy_id: str
    universe: str
    top_n: int
    wf_positive_rate: float
    psr: float
    dsr: float
    lookback: int = 126
    provisional: bool = False


_DEFAULT_CONFIG_PATH = (
    Path(__file__).resolve().parent.parent / "config" / "validated_strategies.json"
)

# DCF credibility band: if the model's fair value falls outside [0.5x, 2.0x] of the
# market price, treat it as not credible. The naive single-stage DCF systematically
# underestimates high-growth megacaps, and the validated edge is the AQR rank — not
# this valuation overlay — so we fall back to a volatility band around the price.
_CREDIBLE_LOW = 0.5
_CREDIBLE_HIGH = 2.0

# A cross-sectional AQR rank is undefined for fewer than this many names.
_MIN_UNIVERSE = 2

# Explicit, recorded DCF assumptions (project rule: valuation inputs must be reproducible).
# net_debt uses GROSS debt because FundamentalRecord has no cash field yet — this
# understates fair value for cash-rich names and is a known P2 (data-layer) limitation.
_DCF_GROWTH = 0.05
_DCF_WACC = 0.09
_DCF_TERMINAL_GROWTH = 0.025
_DCF_YEARS = 5


def _positive_count(values: list[float]) -> int:
    return sum(1 for value in values if value > 0)


def load_validated_strategy(
    strategy_id: str | None = None,
    *,
    path: Path | str | None = None,
) -> ValidatedStrategy:
    """Load a :class:`ValidatedStrategy` from config/validated_strategies.json.

    The P3 re-validation harness regenerates that file, so reliability stats stay
    tied to the latest out-of-sample evidence rather than hard-coded in code.
    """

    config_path = Path(path) if path is not None else _DEFAULT_CONFIG_PATH
    data = json.loads(config_path.read_text(encoding="utf-8"))
    chosen = strategy_id or data.get("default")
    entries = data.get("strategies")
    if not entries:
        raise KeyError(f"'strategies' key missing or empty in {config_path}")
    if chosen not in entries:
        raise KeyError(f"strategy '{chosen}' not found in {config_path}")
    entry = entries[chosen]
    provisional = bool(entry.get("provisional", False))
    if provisional:
        warnings.warn(
            f"strategy '{chosen}' PSR/DSR are PROVISIONAL placeholders — run the P3 "
            "re-validation harness before trusting live confidence scores",
            stacklevel=2,
        )
    return ValidatedStrategy(
        strategy_id=entry["strategy_id"],
        universe=entry["universe"],
        top_n=int(entry["top_n"]),
        wf_positive_rate=float(entry["wf_positive_rate"]),
        psr=float(entry["psr"]),
        dsr=float(entry["dsr"]),
        lookback=int(entry.get("lookback", 126)),
        provisional=provisional,
    )


@dataclass(frozen=True)
class ChartSummary:
    """An advisory, never-binding snapshot of the chart-reading engine's entry timing read.

    This is METADATA ONLY: it never feeds ``_decide_action`` / action / confidence / rank.
    It answers a different question from the AQR signal ("is *now* a good moment to add?"),
    so it is surfaced as context for the human, not as a gate on the recommendation.
    ``confluence`` is the engine's 0–100 score; ``decision`` / ``trend_bias`` are the raw
    enum values (e.g. ``"SCALE_IN"`` / ``"BULLISH"``); ``note`` is a one-line Korean summary.
    """

    decision: str
    confluence: float
    trend_bias: str
    direction: str
    note: str


def chart_confirmation(bars: list[PriceBar], direction: str = "long") -> ChartSummary | None:
    """Run the chart-reading engine over ``bars`` and return an ADVISORY ``ChartSummary``.

    Returns ``None`` (no chart opinion) when there is too little history
    (``< _MIN_CHART_BARS`` bars) or when the chart engine raises for ANY reason — a chart
    failure must NEVER be able to break a recommendation, so every exception is swallowed.
    The result is advisory metadata only and must not influence action/confidence/rank.
    """

    if len(bars) < _MIN_CHART_BARS:
        return None
    try:
        # Local import keeps the engine.chart dependency optional: the recommender works
        # (and its default output is byte-identical) even if the chart engine is absent.
        from engine.chart.read import read_chart

        read = read_chart(bars, direction=direction)
        decision = read.decision.value
        confluence = float(read.confluence)
        trend_bias = read.trend_bias.value
        note = (
            f"차트 타이밍: {decision} (컨플루언스 {confluence:.0f}/100, "
            f"HTF 추세 {trend_bias}) — 참고용, 추천 결정에는 미반영"
        )
        return ChartSummary(
            decision=decision,
            confluence=confluence,
            trend_bias=trend_bias,
            direction=direction,
            note=note,
        )
    except Exception:  # noqa: BLE001 — advisory overlay must never break the recommendation
        return None


@dataclass(frozen=True)
class AQREvaluation:
    ticker: str
    market: str
    as_of: datetime
    in_validated_universe: bool
    rank: int | None
    percentile: float
    universe_size: int
    in_top_n: bool
    composite: float | None
    momentum: float | None
    value: float | None
    quality: float | None
    current_price: float | None
    fair_value: float | None
    fair_value_dispersion: float | None
    valuation_credible: bool
    entry_plan: EntryPlanRecord | None
    confidence: ConfidenceBreakdown
    action: str
    reasons: tuple[str, ...]
    chart_summary: ChartSummary | None = None


def _fair_value(
    fundamentals: FundamentalRecord | None,
    current_price: float,
    *,
    peer_pe: list[float] | None,
    peer_pb: list[float] | None,
) -> tuple[float | None, float | None, int, int]:
    """Best-effort fair value from DCF + multiples.

    Returns ``(fair, dispersion, peer_count, method_count)`` where ``method_count`` is
    the number of methods that produced a positive estimate (a single-method estimate
    has no cross-check, so the caller must not treat it as high-confidence).
    """

    values: dict[str, float | None] = {}
    peer_count = 0
    if fundamentals is not None:
        if (
            fundamentals.free_cash_flow is not None
            and fundamentals.shares_out is not None
            and fundamentals.shares_out > 0
        ):
            # net_debt uses gross debt (no cash field yet) — see _DCF_ASSUMPTIONS note.
            net_debt = fundamentals.total_debt or 0.0
            with contextlib.suppress(ValueError):
                values["dcf"] = discounted_cash_flow(
                    free_cash_flow=fundamentals.free_cash_flow,
                    shares_out=fundamentals.shares_out,
                    net_debt=net_debt,
                    growth=_DCF_GROWTH,
                    wacc=_DCF_WACC,
                    terminal_growth=_DCF_TERMINAL_GROWTH,
                    years=_DCF_YEARS,
                ).fair_value
        if peer_pe and fundamentals.eps is not None and fundamentals.eps > 0:
            values["pe"] = fair_value_from_pe(eps=fundamentals.eps, peer_pe=peer_pe)
            peer_count = max(peer_count, _positive_count(peer_pe))
        if (
            peer_pb
            and fundamentals.total_equity is not None
            and fundamentals.shares_out
            and fundamentals.shares_out > 0
        ):
            book_value_per_share = fundamentals.total_equity / fundamentals.shares_out
            values["pb"] = fair_value_from_pb(
                book_value_per_share=book_value_per_share, peer_pb=peer_pb
            )
            peer_count = max(peer_count, _positive_count(peer_pb))

    positive = [value for value in values.values() if value and value > 0]
    method_count = len(positive)
    if method_count == 0:
        return None, None, peer_count, 0
    fair, dispersion = composite_fair_value(values)
    return fair, dispersion, peer_count, method_count


def _decide_action(*, in_validated_universe: bool, in_top_n: bool, band: str) -> str:
    """Map (universe membership, strategy-holding, confidence band) to an action.

    The ACTION follows the validated signal: a name inside the strategy's top-N is one
    it actually holds, so it is a BUY (the confidence band, a separate axis, conveys how
    much corroboration there is). A low-confidence top-N name is downgraded to HOLD.
    Names outside the top-N but still ranking well are HOLD (watch); the rest AVOID.
    Aligned with the bands so the action never contradicts the band.
    """

    if not in_validated_universe:
        return "AVOID"
    if in_top_n:
        return "BUY" if band in {"high", "medium"} else "HOLD"
    if band in {"high", "medium"}:
        return "HOLD"
    return "AVOID"


def evaluate_ticker(
    *,
    ticker: str,
    bars_by_symbol: dict[str, list[PriceBar]],
    fundamentals_by_symbol: dict[str, FundamentalRecord],
    strategy: ValidatedStrategy,
    peer_pe: list[float] | None = None,
    peer_pb: list[float] | None = None,
    margin_of_safety: float = 0.25,
    asof_ts: datetime | None = None,
    bars: list[PriceBar] | None = None,
    with_chart: bool = False,
) -> AQREvaluation:
    """Fuse the validated AQR rank, a fair-value band, and a laddered entry plan.

    Single-ticker evaluation is computed against the WHOLE universe (the AQR signal is
    cross-sectional), so it is identical work to a full-universe scan. Confidence is
    calibrated from the validated strategy's statistics, and names outside the
    validated universe are reported as AVOID with hard-capped confidence.

    When ``with_chart`` is True, an ADVISORY chart-timing read is attached as
    ``AQREvaluation.chart_summary`` (using ``bars`` if supplied, else the ticker's own
    series from ``bars_by_symbol``). It is metadata only and NEVER affects action /
    confidence / rank; ``with_chart=False`` (the default) produces output identical to
    before, with ``chart_summary=None``.
    """

    symbol = ticker.upper()
    ordered = sorted(bars_by_symbol.get(symbol, []), key=lambda bar: bar.ts)
    ranked = aqr_rank_for(
        symbol, bars_by_symbol, fundamentals_by_symbol, lookback=strategy.lookback
    )

    chart_summary: ChartSummary | None = None
    if with_chart:
        chart_bars = bars if bars is not None else ordered
        chart_summary = chart_confirmation(chart_bars)

    return _build_evaluation(
        symbol=symbol,
        ranked=ranked,
        ordered=ordered,
        fundamentals=fundamentals_by_symbol.get(symbol),
        strategy=strategy,
        peer_pe=peer_pe,
        peer_pb=peer_pb,
        margin_of_safety=margin_of_safety,
        asof_ts=asof_ts,
        universe_fallback_size=len(bars_by_symbol),
        chart_summary=chart_summary,
    )


def _build_evaluation(
    *,
    symbol: str,
    ranked: RankedFactor | None,
    ordered: list[PriceBar],
    fundamentals: FundamentalRecord | None,
    strategy: ValidatedStrategy,
    peer_pe: list[float] | None,
    peer_pb: list[float] | None,
    margin_of_safety: float,
    asof_ts: datetime | None,
    universe_fallback_size: int,
    chart_summary: ChartSummary | None = None,
) -> AQREvaluation:
    """Fuse a precomputed AQR rank, a fair-value band, and a laddered entry plan.

    The AQR signal is cross-sectional, so the rank is computed once (per-ticker via
    aqr_rank_for, or once for the whole universe via aqr_ranked) and passed in here.
    Names outside the validated universe are reported AVOID with hard-capped confidence.

    ``chart_summary`` is optional ADVISORY metadata attached verbatim to the result; it
    is never consulted by ``_decide_action`` or the confidence model, so it cannot change
    the action / confidence / rank.
    """

    # A cross-sectional signal needs something to rank against: a single-name universe
    # is not a validated context, so it must not earn in-universe confidence.
    in_validated_universe = ranked is not None and ranked.universe_size >= _MIN_UNIVERSE
    current_price = ordered[-1].close if ordered else None
    market = ordered[-1].market if ordered else "us"
    as_of = asof_ts or (
        datetime.combine(ordered[-1].ts, datetime.min.time()) if ordered else datetime.now()
    )

    fair_value: float | None = None
    dispersion: float | None = None
    peer_count = 0
    entry_plan: EntryPlanRecord | None = None
    valuation_confidence = "low"
    valuation_credible = False

    if current_price is not None and current_price > 0:
        fair_value, dispersion, peer_count, method_count = _fair_value(
            fundamentals, current_price, peer_pe=peer_pe, peer_pb=peer_pb
        )
        valuation_credible = (
            fair_value is not None
            and _CREDIBLE_LOW * current_price <= fair_value <= _CREDIBLE_HIGH * current_price
        )
        if not valuation_credible:
            valuation_confidence = "low"
        elif method_count >= 2:
            # Two+ independent methods -> dispersion between them is meaningful.
            valuation_confidence = confidence_from_dispersion(dispersion or 0.0, peer_count)
        else:
            # A single credible method has no cross-check: neutral, never "high".
            valuation_confidence = "medium"
        # The validated edge is MOMENTUM, not value-reversion, so the entry ladder is
        # always a volatility band around the current price (buy on dips). DCF fair value
        # is reported only as context (cheap/expensive); it never drives entry/target,
        # which avoids fair-value targets sitting below the price of a momentum winner.
        highs = [bar.high for bar in ordered]
        lows = [bar.low for bar in ordered]
        closes = [bar.close for bar in ordered]
        atr_pct = average_true_range_pct(highs, lows, closes) if len(closes) >= 2 else 0.02
        entry_plan = make_entry_plan(
            symbol=symbol,
            market=market,
            current_price=current_price,
            fair_value=current_price,
            atr_pct=atr_pct,
            asof_ts=as_of,
            margin_of_safety=margin_of_safety,
        )

    percentile = ranked.percentile if ranked else 0.0
    rank = ranked.rank if ranked else None
    universe_size = ranked.universe_size if ranked else universe_fallback_size
    in_top_n = bool(ranked and ranked.rank <= strategy.top_n)

    confidence = calibrated_confidence(
        aqr_percentile=percentile,
        in_validated_universe=in_validated_universe,
        wf_positive_rate=strategy.wf_positive_rate,
        psr=strategy.psr,
        dsr=strategy.dsr,
        valuation_confidence=valuation_confidence,
        provisional=strategy.provisional,
    )

    action = _decide_action(
        in_validated_universe=in_validated_universe,
        in_top_n=in_top_n,
        band=confidence.band,
    )

    reasons: list[str] = []
    if in_validated_universe and rank is not None:
        reasons.append(
            f"AQR rank {rank}/{universe_size} on '{strategy.universe}' "
            f"(top-{strategy.top_n} = strategy holdings)"
        )
    else:
        reasons.append(
            f"'{symbol}' is not in the validated universe '{strategy.universe}' — "
            "no proven forward edge"
        )
    if fair_value is not None and current_price:
        discount = (fair_value - current_price) / current_price
        suffix = "" if valuation_credible else " — naive DCF, not credible"
        reasons.append(
            f"DCF fair value (context) {fair_value:.2f} vs price {current_price:.2f} "
            f"({discount:+.0%}){suffix}"
        )
    reasons.extend(confidence.reasons)

    return AQREvaluation(
        ticker=symbol,
        market=market,
        as_of=as_of,
        in_validated_universe=in_validated_universe,
        rank=rank,
        percentile=percentile,
        universe_size=universe_size,
        in_top_n=in_top_n,
        composite=ranked.score.composite if ranked else None,
        momentum=ranked.score.momentum if ranked else None,
        value=ranked.score.value if ranked else None,
        quality=ranked.score.quality if ranked else None,
        current_price=current_price,
        fair_value=fair_value,
        fair_value_dispersion=dispersion,
        valuation_credible=valuation_credible,
        entry_plan=entry_plan,
        confidence=confidence,
        action=action,
        reasons=tuple(reasons),
        chart_summary=chart_summary,
    )


def format_evaluation(result: AQREvaluation) -> str:
    """Render an :class:`AQREvaluation` as an investor-facing markdown report."""

    lines: list[str] = []
    lines.append(
        f"# {result.ticker} — {result.action}  (신뢰도/Confidence: {result.confidence.band})"
    )
    lines.append("")
    lines.append(f"- as of: {result.as_of:%Y-%m-%d}")
    lines.append(
        f"- Confidence score: {result.confidence.score:.0f}/100 ({result.confidence.band})"
    )

    lines.append("")
    lines.append("## AQR rank (validated signal)")
    if result.in_validated_universe and result.rank is not None:
        lines.append(
            f"- AQR rank: **{result.rank}/{result.universe_size}** "
            f"(percentile {result.percentile:.0f}; in strategy holdings: {result.in_top_n})"
        )
        lines.append(
            f"- factors — momentum {result.momentum:+.2%} | "
            f"value(EY) {result.value:+.4f} | quality {result.quality:+.4f} | "
            f"composite {result.composite:+.2f}"
        )
    else:
        lines.append(
            "- not in the validated universe — **no proven forward edge** (treat as AVOID)"
        )

    lines.append("")
    lines.append("## Valuation context & entry (평균매수단가)")
    if result.fair_value is not None and result.current_price is not None:
        discount = (result.fair_value - result.current_price) / result.current_price
        stance = "cheap vs DCF" if discount > 0 else "expensive vs DCF"
        credibility = " (credible)" if result.valuation_credible else " ⚠️ not credible (naive DCF)"
        lines.append(f"- current price: {result.current_price:.2f}")
        lines.append(
            f"- DCF fair value (context only): {result.fair_value:.2f} "
            f"({discount:+.0%} vs price → {stance}){credibility}"
        )
        lines.append(
            f"- DCF inputs: WACC {_DCF_WACC:.0%}, growth {_DCF_GROWTH:.0%}, "
            f"terminal {_DCF_TERMINAL_GROWTH:.1%}, {_DCF_YEARS}y; net_debt = gross debt "
            "(cash not subtracted — P2 limitation, understates cash-rich names)"
        )
    lines.append(
        "- note: this is a MOMENTUM strategy — the entry band is volatility-based around "
        "the current price; DCF fair value above is context, not the entry/exit driver"
    )
    if result.entry_plan is not None:
        plan = result.entry_plan
        lines.append(f"- **target avg entry (평균매수단가): {plan.target_entry:.2f}**")
        lines.append(
            f"- stop loss: {plan.stop_loss:.2f} | target exit: {plan.target_exit:.2f} "
            "(generic +15% momentum target, not a fair-value target)"
        )
        lines.append(f"- risk/reward: {plan.risk_reward:.2f} (vs the volatility-based entry)")
        lines.append(
            "- ⚠️ stop/entry from close-only snapshot ATR (intraday range not captured; "
            "stops may need widening)"
        )
        lines.append("- entry ladder:")
        try:
            steps: list[dict[str, Any]] = json.loads(plan.ladder_json)
        except (ValueError, TypeError):
            steps = []
        for step in steps:
            lines.append(
                f"    - {float(step['price']):.2f}  (weight {float(step['weight']):.0%}) — {step.get('reason', '')}"
            )
    else:
        lines.append("- entry plan unavailable (insufficient price/fundamental data)")

    # Advisory-only: rendered ONLY when a chart read was attached. Default output (no
    # chart) is byte-identical to before, so existing reports are unchanged.
    if result.chart_summary is not None:
        cs = result.chart_summary
        lines.append("")
        lines.append("## 차트 타이밍 (참고용 · advisory)")
        lines.append(f"- {cs.note} (방향 {cs.direction}; 추천 action/confidence/rank에는 미반영)")

    lines.append("")
    lines.append("## Why")
    for reason in result.reasons:
        lines.append(f"- {reason}")

    return "\n".join(lines)


def scan_universe(
    *,
    bars_by_symbol: dict[str, list[PriceBar]],
    fundamentals_by_symbol: dict[str, FundamentalRecord],
    strategy: ValidatedStrategy,
    peer_pe: list[float] | None = None,
    peer_pb: list[float] | None = None,
    margin_of_safety: float = 0.25,
    asof_ts: datetime | None = None,
    with_chart: bool = False,
) -> list[AQREvaluation]:
    """Rank the WHOLE validated universe once and evaluate every name (best-first).

    The AQR composite is cross-sectional, so the universe is ranked in a single pass
    and each name then gets its fair-value band, entry ladder and calibrated
    confidence. This is the honest answer to "evaluate all tickers, not a handful" —
    but it is meaningful ONLY for the validated universe; the strategy has no proven
    edge over names it was never validated on.

    ``with_chart`` (default False) attaches the same ADVISORY chart-timing read per name
    as ``evaluate_ticker``; it never influences action / confidence / rank or the order.
    """

    ranked_list = aqr_ranked(bars_by_symbol, fundamentals_by_symbol, lookback=strategy.lookback)
    fallback = len(bars_by_symbol)
    results: list[AQREvaluation] = []
    for ranked in ranked_list:
        sym = ranked.score.symbol.upper()
        ordered = sorted(bars_by_symbol.get(sym, []), key=lambda bar: bar.ts)
        chart_summary = chart_confirmation(ordered) if with_chart else None
        results.append(
            _build_evaluation(
                symbol=sym,
                ranked=ranked,
                ordered=ordered,
                fundamentals=fundamentals_by_symbol.get(sym),
                strategy=strategy,
                peer_pe=peer_pe,
                peer_pb=peer_pb,
                margin_of_safety=margin_of_safety,
                asof_ts=asof_ts,
                universe_fallback_size=fallback,
                chart_summary=chart_summary,
            )
        )
    return results


def format_scan(results: list[AQREvaluation], *, top: int = 20) -> str:
    """Render a ranked scan as a markdown table; ★ marks the strategy's holdings."""

    universe_size = results[0].universe_size if results else 0
    buys = sum(1 for r in results if r.action == "BUY")
    holds = sum(1 for r in results if r.action == "HOLD")

    # Advisory chart column appears ONLY when at least one row carries a chart read, so
    # the default (no chart) table is byte-identical to before.
    show_chart = any(r.chart_summary is not None for r in results)

    lines: list[str] = []
    lines.append(f"# Validated universe scan — {len(results)} names ranked (top {top} shown)")
    lines.append("")
    lines.append(f"- universe size: {universe_size} | BUY: {buys} | HOLD: {holds}")
    lines.append("")
    if show_chart:
        lines.append(
            "| rank | ticker | action | conf | pct | price | avg entry | stop | target "
            "| chart(참고용) |"
        )
        lines.append("|--:|:--|:--|:--|--:|--:|--:|--:|--:|:--|")
    else:
        lines.append("| rank | ticker | action | conf | pct | price | avg entry | stop | target |")
        lines.append("|--:|:--|:--|:--|--:|--:|--:|--:|--:|")
    for result in results[:top]:
        plan = result.entry_plan
        avg_entry = f"{plan.target_entry:.2f}" if plan else "—"
        stop = f"{plan.stop_loss:.2f}" if plan else "—"
        target = f"{plan.target_exit:.2f}" if plan else "—"
        price = f"{result.current_price:.2f}" if result.current_price is not None else "—"
        star = "★" if result.in_top_n else ""
        row = (
            f"| {result.rank}{star} | {result.ticker} | {result.action} "
            f"| {result.confidence.band} | {result.percentile:.0f} | {price} "
            f"| {avg_entry} | {stop} | {target} |"
        )
        if show_chart:
            cs = result.chart_summary
            chart_cell = f"{cs.decision} {cs.confluence:.0f}" if cs is not None else "—"
            row += f" {chart_cell} |"
        lines.append(row)
    lines.append("")
    lines.append("★ = within the strategy's top-N holdings (the names it would actually buy).")

    provisional = next(
        (
            reason
            for result in results
            for reason in result.confidence.reasons
            if "provisional" in reason.lower()
        ),
        None,
    )
    if provisional:
        lines.append("")
        lines.append(f"⚠️ {provisional.strip()}")
    return "\n".join(lines)
